### PR TITLE
Uncondensed Dashboard - Manual Update

### PR DESCRIPTION
**Pull request by joshchyeonlee**
- Disabled dates that fall outside of the "sevenDaysArray" mock data dates
- Updates values on graph for Uncondesned Dashboard
- Cancel brings back to Uncondensed Dashboard
- X closes modal
- Fixed date difference bug

Screenshot 2023-11-19 at 11 34 18 AM

Video too large for github:
https://drive.google.com/file/d/17u4jEIoPZ1LUG298iFf6goKZ2rEbk8t8/view?usp=sharing

## Update
- Changed graph arrow buttons to be used for pagination
- Updated size of mock data to enable pagination
- Made component responsive

### CODE REVIEW

**Review by zhifanl — APPROVED** [review]

**Comment by abenavidesaguirre** [comment]
Can we remove the background colour on the date picker and maybe center the alignment more? I have an example on the nutrition dashboard if you want to take a look at that

**Comment by abenavidesaguirre** [comment]
Can we also center the text for the step input more? And just a reminder to add a task to the trello to update the hardcoding of the end adornment

**Comment by abenavidesaguirre** [comment]
Since the user has to click on update manually from the widget when a date is already selected, do they need to be able to change the date again?

**Comment by joshchyeonlee** [comment]
> Since the user has to click on update manually from the widget when a date is already selected, do they need to be able to change the date again?

stole the sx from that page lol
Screenshot 2023-11-28 at 6 30 00 PM

**Comment by joshchyeonlee** [comment]
> Can we also center the text for the step input more? And just a reminder to add a task to the trello to update the hardcoding of the end adornment

done

> Since the user has to click on update manually from the widget when a date is already selected, do they need to be able to change the date again?

removed

Screenshot 2023-11-28 at 6 36 57 PM

**Pull request merged**
